### ISSUE TITLE
Ally bug? #2

### ISSUE THREAD

**Issue by LOOOOOOOL** [drtshock/HCFProblems#99]
The ally bug is occurring again.

http://gyazo.com/f665c00617d0306afc546abe069dd077

Version: 37

**Comment by nsporillo** [comment]
Did you happen to try to replicate the bug before making the ticket? 

That faction likely already had 3. The fix we applied only prevents it from happening again.

At any rate, you can go into the factions.json (don't edit it with the server using it, either shut down or take a copy and edit that, then replace old) and remove the 3rd ally.

**Comment by TMNetwork** [comment]
@nsporillo ill see

**Comment by nsporillo** [comment]
@TMNetwork Yeah, the bug should have been patched but our fix did not go through all factions and remove allies if they were above the limit.

**Comment by TMNetwork** [comment]
@nsporillo ill update u by tomorrow, sound good?

**Comment by nsporillo** [comment]
@TMNetwork Yeah, I'll leave this open even though I'm fairly certain the bug was fixed.

**Comment by nsporillo** [comment]
@TMNetwork closing since no reply. If you still have this issue, reply to this issue

**Comment by nsporillo** [comment]
@TMNetwork Update the original post on this issue with how to replicate this bug. When I fixed it the first time I tried a set of steps that verified the fix worked. 

If you can't replicate this issue on the latest build, then how can you say it's still a bug and not factions who HAD 3 allies and after the patch still DO...?

**Comment by TMNetwork** [comment]
I have the latest and people are still getting 3 allied factions.

**Comment by nsporillo** [comment]
![dude..](http://puu.sh/h5ibT/1c3e8df07a.png)

If you cannot explain how to replicate this issue, how do you expect me to fix it? I already told you I went through myself and fixed it the first time around (implies I did not find another case 3 allies could be done).

**Comment by NauruMC** [comment]
@nsporillo Maybe his players just have magical powers, or there is a new hack in the Nodus client called 'HCFactions bypass 2 ally limit v1.2'...

This was intended as humor.

**Comment by TMNetwork** [comment]
I'm still trying to find out how but it still works. I saw a new fac make a
faction and then triple ally with some others.

**Comment by nsporillo** [comment]
Closed, due to inactivity...

When you can confirm this issue exists, just make a new issue on the tracker for it.

Try to include the steps you took to reproduce the error, so when I make a fix I can debug myself.
